//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("mvcEstudiantesModel", "FK_EstudianteAsignatura_Asignaturas", "Asignaturas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mvcEstudiantes.Models.Asignaturas), "EstudianteAsignatura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mvcEstudiantes.Models.EstudianteAsignatura), true)]
[assembly: EdmRelationshipAttribute("mvcEstudiantesModel", "FK_EstudianteAsignatura_Estudiante", "Estudiante", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mvcEstudiantes.Models.Estudiante), "EstudianteAsignatura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mvcEstudiantes.Models.EstudianteAsignatura), true)]

#endregion

namespace mvcEstudiantes.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class mvcEstudiantesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mvcEstudiantesEntities object using the connection string found in the 'mvcEstudiantesEntities' section of the application configuration file.
        /// </summary>
        public mvcEstudiantesEntities() : base("name=mvcEstudiantesEntities", "mvcEstudiantesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mvcEstudiantesEntities object.
        /// </summary>
        public mvcEstudiantesEntities(string connectionString) : base(connectionString, "mvcEstudiantesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mvcEstudiantesEntities object.
        /// </summary>
        public mvcEstudiantesEntities(EntityConnection connection) : base(connection, "mvcEstudiantesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Asignaturas> Asignaturas
        {
            get
            {
                if ((_Asignaturas == null))
                {
                    _Asignaturas = base.CreateObjectSet<Asignaturas>("Asignaturas");
                }
                return _Asignaturas;
            }
        }
        private ObjectSet<Asignaturas> _Asignaturas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Estudiante> Estudiante
        {
            get
            {
                if ((_Estudiante == null))
                {
                    _Estudiante = base.CreateObjectSet<Estudiante>("Estudiante");
                }
                return _Estudiante;
            }
        }
        private ObjectSet<Estudiante> _Estudiante;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EstudianteAsignatura> EstudianteAsignatura
        {
            get
            {
                if ((_EstudianteAsignatura == null))
                {
                    _EstudianteAsignatura = base.CreateObjectSet<EstudianteAsignatura>("EstudianteAsignatura");
                }
                return _EstudianteAsignatura;
            }
        }
        private ObjectSet<EstudianteAsignatura> _EstudianteAsignatura;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Asignaturas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAsignaturas(Asignaturas asignaturas)
        {
            base.AddObject("Asignaturas", asignaturas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Estudiante EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstudiante(Estudiante estudiante)
        {
            base.AddObject("Estudiante", estudiante);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EstudianteAsignatura EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstudianteAsignatura(EstudianteAsignatura estudianteAsignatura)
        {
            base.AddObject("EstudianteAsignatura", estudianteAsignatura);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mvcEstudiantesModel", Name="Asignaturas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Asignaturas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Asignaturas object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="horario">Initial value of the Horario property.</param>
        public static Asignaturas CreateAsignaturas(global::System.Int32 id, global::System.String nombre, global::System.String horario)
        {
            Asignaturas asignaturas = new Asignaturas();
            asignaturas.ID = id;
            asignaturas.Nombre = nombre;
            asignaturas.Horario = horario;
            return asignaturas;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Horario
        {
            get
            {
                return _Horario;
            }
            set
            {
                OnHorarioChanging(value);
                ReportPropertyChanging("Horario");
                _Horario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Horario");
                OnHorarioChanged();
            }
        }
        private global::System.String _Horario;
        partial void OnHorarioChanging(global::System.String value);
        partial void OnHorarioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mvcEstudiantesModel", "FK_EstudianteAsignatura_Asignaturas", "EstudianteAsignatura")]
        public EntityCollection<EstudianteAsignatura> EstudianteAsignatura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EstudianteAsignatura>("mvcEstudiantesModel.FK_EstudianteAsignatura_Asignaturas", "EstudianteAsignatura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EstudianteAsignatura>("mvcEstudiantesModel.FK_EstudianteAsignatura_Asignaturas", "EstudianteAsignatura", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mvcEstudiantesModel", Name="Estudiante")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estudiante : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Estudiante object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="cedula">Initial value of the Cedula property.</param>
        public static Estudiante CreateEstudiante(global::System.Int32 id, global::System.String nombre, global::System.String apellido, global::System.String cedula)
        {
            Estudiante estudiante = new Estudiante();
            estudiante.ID = id;
            estudiante.Nombre = nombre;
            estudiante.Apellido = apellido;
            estudiante.Cedula = cedula;
            return estudiante;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                OnCedulaChanging(value);
                ReportPropertyChanging("Cedula");
                _Cedula = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cedula");
                OnCedulaChanged();
            }
        }
        private global::System.String _Cedula;
        partial void OnCedulaChanging(global::System.String value);
        partial void OnCedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaNacimiento
        {
            get
            {
                return _FechaNacimiento;
            }
            set
            {
                OnFechaNacimientoChanging(value);
                ReportPropertyChanging("FechaNacimiento");
                _FechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNacimiento");
                OnFechaNacimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaNacimiento;
        partial void OnFechaNacimientoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaNacimientoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mvcEstudiantesModel", "FK_EstudianteAsignatura_Estudiante", "EstudianteAsignatura")]
        public EntityCollection<EstudianteAsignatura> EstudianteAsignatura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EstudianteAsignatura>("mvcEstudiantesModel.FK_EstudianteAsignatura_Estudiante", "EstudianteAsignatura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EstudianteAsignatura>("mvcEstudiantesModel.FK_EstudianteAsignatura_Estudiante", "EstudianteAsignatura", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mvcEstudiantesModel", Name="EstudianteAsignatura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EstudianteAsignatura : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EstudianteAsignatura object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iDEstudiante">Initial value of the IDEstudiante property.</param>
        /// <param name="iDAsignatura">Initial value of the IDAsignatura property.</param>
        public static EstudianteAsignatura CreateEstudianteAsignatura(global::System.Int32 id, global::System.Int32 iDEstudiante, global::System.Int32 iDAsignatura)
        {
            EstudianteAsignatura estudianteAsignatura = new EstudianteAsignatura();
            estudianteAsignatura.ID = id;
            estudianteAsignatura.IDEstudiante = iDEstudiante;
            estudianteAsignatura.IDAsignatura = iDAsignatura;
            return estudianteAsignatura;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDEstudiante
        {
            get
            {
                return _IDEstudiante;
            }
            set
            {
                OnIDEstudianteChanging(value);
                ReportPropertyChanging("IDEstudiante");
                _IDEstudiante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDEstudiante");
                OnIDEstudianteChanged();
            }
        }
        private global::System.Int32 _IDEstudiante;
        partial void OnIDEstudianteChanging(global::System.Int32 value);
        partial void OnIDEstudianteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDAsignatura
        {
            get
            {
                return _IDAsignatura;
            }
            set
            {
                OnIDAsignaturaChanging(value);
                ReportPropertyChanging("IDAsignatura");
                _IDAsignatura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDAsignatura");
                OnIDAsignaturaChanged();
            }
        }
        private global::System.Int32 _IDAsignatura;
        partial void OnIDAsignaturaChanging(global::System.Int32 value);
        partial void OnIDAsignaturaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mvcEstudiantesModel", "FK_EstudianteAsignatura_Asignaturas", "Asignaturas")]
        public Asignaturas Asignaturas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Asignaturas>("mvcEstudiantesModel.FK_EstudianteAsignatura_Asignaturas", "Asignaturas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Asignaturas>("mvcEstudiantesModel.FK_EstudianteAsignatura_Asignaturas", "Asignaturas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Asignaturas> AsignaturasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Asignaturas>("mvcEstudiantesModel.FK_EstudianteAsignatura_Asignaturas", "Asignaturas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Asignaturas>("mvcEstudiantesModel.FK_EstudianteAsignatura_Asignaturas", "Asignaturas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mvcEstudiantesModel", "FK_EstudianteAsignatura_Estudiante", "Estudiante")]
        public Estudiante Estudiante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estudiante>("mvcEstudiantesModel.FK_EstudianteAsignatura_Estudiante", "Estudiante").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estudiante>("mvcEstudiantesModel.FK_EstudianteAsignatura_Estudiante", "Estudiante").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estudiante> EstudianteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estudiante>("mvcEstudiantesModel.FK_EstudianteAsignatura_Estudiante", "Estudiante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estudiante>("mvcEstudiantesModel.FK_EstudianteAsignatura_Estudiante", "Estudiante", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
